# use java support.

language: java
sudo: required
install: true

jdk:
  - openjdk11

before_install:
  - "chmod +x gradlew"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

os:
  - linux
